"""
Django settings for NewsAndCommentsProject project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i%8h&3pi_m9kd2gly&ou_rjr8ta)h$3auh7f4&rt#$$u571y+c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'news.apps.NewsConfig',
    'django.contrib.sites',
    'django.contrib.flatpages',
    "django_filters",
    'django_apscheduler',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    "sign",
    "protect"
]


SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware'
]

ROOT_URLCONF = 'NewsAndCommentsProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsAndCommentsProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = '/accounts/login/' #'sign/login/'
LOGIN_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         }
#     }
# }
#
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'

ACCOUNT_FORMS = {'signup': 'sign.models.CommonSignupForm'}


EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'viktorsung'
EMAIL_HOST_PASSWORD = 'PasswordForDjango'
EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = 'victorsung@yandex.ru'

#формат даты
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
#скип зпдпчи если не сделалась за 60 сек
APSCHEDULER_RUN_NOW_TIMEOUT = 60

# redis

CELERY_BROKER_URL = 'redis://default:PwtPgYUEAWvmLd14AlpCOzLlMjR4xp9t@redis-14993.c275.us-east-1-4.ec2.cloud.redislabs.com:14993'
CELERY_RESULT_BACKEND = 'redis://default:PwtPgYUEAWvmLd14AlpCOzLlMjR4xp9t@redis-14993.c275.us-east-1-4.ec2.cloud.redislabs.com:14993'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


#кеши

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'),
    }
}


#logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'style' : '{',
    'formatters': {
        'general': {
            'format': '%(asctime)s %(name)s %(module) (levelname)s '
            # времени, уровня логирования, модуля, в котором возникло сообщение
        },
        'errors': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s '
            # время, уровень логирования, само сообщение, путь к источнику сообщения и стэк ошибки.
        },
        'security': {
            'format': '%(asctime)s %(levelname)s %(message)s %(module)s'
            # время, уровень логирования, модуль и сообщение.
        },
        'debug_console': {
            'format': '%(asctime)s %(levelname)s  %(message)s'
            # время, уровень сообщения, сообщения.
        },
        'warning_console': {
            'format': '%(asctime)s %(levelname)s  %(message)s %(pathname)s'
            # время, уровень сообщения, сообщения  путь к источнику события
        },
        'error_console': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s'
            # время, уровень сообщения, сообщения  путь к источнику события, стэк ошибки
        },

    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        },
    },
    'handlers': {
        'console_debug': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'debug_console'
        },
        'console_warning':{
            'level': 'WARNING',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'warning_console'
        },
        'console_error':{
            'level': 'ERROR',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'error_console'
        },
        'generallog':{
            'level': 'INFO',
            'filters': ['require_debug_false'],
            'class': 'logging.FileHandler',
            'formatter': 'general',
            'filename': 'general.log'
        },
        'errorslog':{
            'level': 'ERROR',
            #'filters': ['require_debug_false'],
            'class': 'logging.FileHandler',
            'formatter': 'errors',
            'filename': 'errors.log'
        },
        'securitylog':{
            'level': 'INFO',
            #'filters': ['require_debug_false'],
            'class': 'logging.FileHandler',
            'formatter': 'security',
            'filename': 'security.log'
        },
        'mail_admins': {
            'level': 'ERROR',
            'formatter': 'errors',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },

    'loggers': {
        'django': {
            'handlers': ['console_debug', 'console_warning', 'console_error','generallog' ],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['errorslog', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['errorslog', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.template': {
            'handlers': ['errorslog'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['errorslog'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['securitylog'],
            'level': 'INFO',
            'propagate': False,
        }
    }
}