# Generated by Django 4.1.5 on 2023-01-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
                ('category.html', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category.html')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='category.html',
            field=models.ManyToManyField(through='news.Subscribers', to='news.category.html'),
        ),
    ]
